function channel = ft_read_chan_tsv(filename)

% Script for importing data from the following text file:
%
%    filename: D:\MATLAB\Analysis\Data\testData\channels.tsv
%
% Auto-generated by MATLAB on 28-Jan-2020 10:07:39

%% Setup the Import Options
opts        = detectImportOptions(filename,'filetype','text');
tsv         = readtable(filename, opts); 
tsv         = table2struct(tsv);

%% Reformat into FT-like structure with cell array
channel = [];

fn = fieldnames(tsv);
for i = 1:length(fn)
    if ischar(tsv(1).(fn{i}))
        channel.(fn{i}) = {tsv(:).(fn{i})}';
    end
end

%% Replace default names with Fieldtrip names
% Replace 'MEG' with 'megmag'
try
    indx = find(contains(channel.type,'MEG'));
    channel.type(indx) = {'megmag'};
catch
    ft_warning('Cannot replace MEG with megmag');
end

% Replace 'REF' with 'refmag'
try
    indx = find(contains(channel.type,'REF'));
    channel.type(indx) = {'refmag'};
catch
    ft_warning('Cannot replace REF with refmag');
end

% Replace 'TRIG' with 'trigger
try
    indx = find(contains(channel.type,'TRIG'));
    channel.type(indx) = {'trigger'};
catch
    ft_warning('Cannot replace TRIG with trigger');
end




