function pos = ft_read_pos_tsv(filename)

% Script for importing data from the following text file:
%
%    filename: D:\MATLAB\Analysis\Data\testData\channels.tsv
%
% Auto-generated by MATLAB on 28-Jan-2020 10:07:39

%% Setup the Import Options
opts                    = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines          = [2, Inf];
opts.Delimiter          = "\t";

% Specify column names and types
opts.VariableNames      = ["label", "Px", "Py", "Pz", "Ox", "Oy", "Oz"];
opts.VariableTypes      = ["string", "double", "double", "double", "double", "double", "double"];
opts                    = setvaropts(opts, 1, "WhitespaceRule", "preserve");
opts                    = setvaropts(opts, [1, 2, 3], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule   = "ignore";
opts.EmptyLineRule      = "read";

% Import the data
posAll                  = table2struct(readtable(filename, opts),'ToScalar',true);
pos.label               = posAll.label;
pos.chanpos             = [posAll.Px posAll.Py posAll.Pz];
pos.chanori             = [posAll.Ox posAll.Oy posAll.Oz];

pos.label = cellstr(pos.label);
end


