function channel = ft_read_chan_tsv(filename)

% Script for importing data from the following text file:
%
%    filename: D:\MATLAB\Analysis\Data\testData\channels.tsv
%
% Auto-generated by MATLAB on 28-Jan-2020 10:07:39

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["label", "chantype", "unit"];
opts.VariableTypes = ["string", "string", "string"];
opts = setvaropts(opts, 1, "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 2, 3], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
channel = table2struct(readtable(filename, opts),'ToScalar',true);

% set MEG = megmag
MEGidx      = ismember(channel.chantype,'MEG');
channel.chantype(MEGidx) = 'megmag';
